.PHONY: build
build:
	cargo build

.PHONY: run
run:
	cargo run

.PHONY: check
check:
	cargo check

.PHONY: release
release:
	cargo build --release

.PHONY: update
update:
	cargo update

.PHONY: docs
docs:
	cargo doc --open

.PHONY: fmt
fmt:
	cargo fmt
